# --- General options --- #

# Name of website
title: Solicitação de compras

# Short description of your site
description: Ajudando as pessoas a manter a quarentena

# Language
lang: pt-BR

repository: matheus-vieira/solicitacao-compra
github: [metadata]

incremental: true
port: 8081
host: 0.0.0.0

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

author:
  name: Matheus Costa Vieira
  email: matheus.costa.vieira@gmail.com

plugins:
  - jekyll-github-metadata
  - uglifier


compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: []

collections:
  estabelecimentos:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "estabelecimentos"
    values:
      layout: "estabelecimentos"


# navbar pages
navbar:
  - slug: contato
    title: Começe aqui
  - slug: estabelecimentos
    title: Estabelecimentos